USE [master]
GO

/****** Object:  Database [BanXe]    Script Date: 3/29/2023 9:01:58 PM ******/
CREATE DATABASE [BanXe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BanXe', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.THINH\MSSQL\DATA\BanXe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BanXe_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.THINH\MSSQL\DATA\BanXe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BanXe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BanXe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BanXe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BanXe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BanXe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BanXe] SET ARITHABORT OFF 
GO

ALTER DATABASE [BanXe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BanXe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BanXe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BanXe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BanXe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BanXe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BanXe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BanXe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BanXe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BanXe] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BanXe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BanXe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BanXe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BanXe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BanXe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BanXe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BanXe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BanXe] SET RECOVERY FULL 
GO

ALTER DATABASE [BanXe] SET  MULTI_USER 
GO

ALTER DATABASE [BanXe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BanXe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BanXe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BanXe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BanXe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BanXe] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BanXe] SET QUERY_STORE = ON
GO

ALTER DATABASE [BanXe] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BanXe] SET  READ_WRITE 
GO

